### ISSUE TITLE
いくつかの行の末尾に不要な空白が入る

### ISSUE THREAD

**Issue by SnO2WMaN** [usagrada/satysfi-formatter#30]
発生条件はわかりませんが，フォーマット時に以下のような空白が行の末尾に入るバグ?が存在します．

![2022_06_29__10_24_58](https://user-images.githubusercontent.com/15155608/176331182-444ad0c9-675b-4d9c-bb2d-79329c5ff34d.png)

VSCodeなどのエディタではこの空白が削除されるため，フォーマット後のファイルと保存後のファイルで若干の違いが発生し，CIがコケるなどの問題が生じます．

**Comment by usagrada** [comment]
ありがとうございます！
フォーマット時のバグですね。
少々解析に時間がかかるかもしれませんが、改善します（解析結果を元に結合し直す実装なので、現状のコードで想定されていないパターンになっている気がしています）。

空白が自動で削除されるのは editorconfig の問題だと思われます（エディターにデフォルトで入っている機能では無いと理解しています）。もし至急対処必要な場合、`.editorconfig` の行末の空白の削除の設定を無効化することで、対処いただきたいです。

```config
[*.{saty,satyh}]
trim_trailing_whitespace = false
```

**Comment by SnO2WMaN** [comment]
迅速な回答ありがとうございます．一旦ローカルでは`.editorconfig`の応急処置で対応します．

**Comment by usagrada** [comment]
ありがとうございます。

#32 の修正で、この問題を修正できたと思っておりますが、ご確認いただけますでしょうか？（テストケースも追記し、デフォルトブランチにマージしましたので、最新のものを入れていただければと思います。）

**Comment by SnO2WMaN** [comment]
いくつかのコメントの処理でまだ空白が入るのではないでしょうか？このファイルに対して処理を掛けているのですが，一部入る気がします．

https://github.com/monaqa/slydifi/blob/e9d0f57c9e27c77888582eaa9ad8b9fd35a12828/doc/slydifi.saty

**Comment by usagrada** [comment]
ありがとうございます。
確認したところ、確かに空白が入ることを確認しました。

前の原因とは別で、コメントの処理自体に問題がありました。
#33 で上記のファイルに対しては空白が入らないことを手元で確認しました(追加で後処理で末尾の空白を除去するような処理も含めたので、これで末尾に空白入ることは無いと思います)。

フォーマット自体の問題はあると思いますが、この問題はこれで大丈夫でしょうか？

**Comment by SnO2WMaN** [comment]
多分これで問題ないと思います．CIでコケる問題は多分こちら側の何らかの設定ミスの可能性が高いようです．

とりあえず，このIssueは解決済みとして一旦閉じます．

**Comment by usagrada** [comment]
ありがとうございます。
また何かあれば、IssueでもPull Requestでもお願いいたします。
